package api

import (
	"github.com/google/uuid"
	"github.com/BlueBeard63/archon/internal/models"
)

// NodeClient defines the interface for communicating with remote node servers
// Nodes are Go services running Docker + Traefik that host sites
type NodeClient interface {
	// Site deployment operations
	DeploySite(endpoint, apiKey string, site *models.Site, domainName string) error
	DeleteSite(endpoint, apiKey string, siteID uuid.UUID) error
	GetSiteStatus(endpoint, apiKey string, siteID uuid.UUID) (*models.SiteStatus, error)
	StopSite(endpoint, apiKey string, siteID uuid.UUID) error
	RestartSite(endpoint, apiKey string, siteID uuid.UUID) error

	// Node health and monitoring
	HealthCheck(endpoint, apiKey string) (*HealthResponse, error)
	GetDockerInfo(endpoint, apiKey string) (*models.DockerInfo, error)
	GetTraefikInfo(endpoint, apiKey string) (*models.TraefikInfo, error)

	// Container monitoring
	GetContainerLogs(endpoint, apiKey string, siteID uuid.UUID, lines int) ([]string, error)
	GetContainerMetrics(endpoint, apiKey string, siteID uuid.UUID) (*ContainerMetrics, error)
}

// DeployRequest is the payload sent to nodes to deploy a site
type DeployRequest struct {
	Name            string              `json:"name"`
	Domain          string              `json:"domain"`
	DockerImage     string              `json:"docker_image"`
	EnvironmentVars map[string]string   `json:"environment_vars"`
	Port            int                 `json:"port"`
	SSLEnabled      bool                `json:"ssl_enabled"`
	ConfigFiles     []models.ConfigFile `json:"config_files"`
	TraefikLabels   map[string]string   `json:"traefik_labels"` // Generated by Site.GenerateTraefikLabels()
}

// HealthResponse contains node health information
type HealthResponse struct {
	Status  models.NodeStatus   `json:"status"`
	Docker  *models.DockerInfo  `json:"docker,omitempty"`
	Traefik *models.TraefikInfo `json:"traefik,omitempty"`
}

// ContainerMetrics contains resource usage for a deployed site
type ContainerMetrics struct {
	CPUPercent     float64 `json:"cpu_percent"`
	MemoryUsage    int64   `json:"memory_usage"`
	MemoryLimit    int64   `json:"memory_limit"`
	NetworkRxBytes int64   `json:"network_rx_bytes"`
	NetworkTxBytes int64   `json:"network_tx_bytes"`
}

// DeployResponse is returned after successfully deploying a site
type DeployResponse struct {
	SiteID      uuid.UUID `json:"site_id"`
	ContainerID string    `json:"container_id"`
	Status      string    `json:"status"`
	Message     string    `json:"message"`
}

// ErrorResponse is the standard error format from node APIs
type ErrorResponse struct {
	Error   string `json:"error"`
	Code    string `json:"code"`
	Details string `json:"details,omitempty"`
}
